import "./globals.css";

import Sidebar from "@/components/Sidebar";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { headers } from "next/headers";

const inter = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const heads = headers();

  const pathname = heads.get("x-current-path");

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full flex">
          <Sidebar pathname={pathname!} />
          <main className="flex flex-1 min-h-screen px-[5px]">
            <div className="bg-[#1B222B] w-full border border-[#283038] p-4">
              {children}
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
